apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kavach-lab
resources:
  - rbac.yaml
  - prometheus.yaml
  - grafana.yaml
configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml
  - name: grafana-datasource
    files:
      - datasource.yaml
